version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: briefcase-server-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/.env:/app/.env:ro
    networks:
      - briefcase-network
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: briefcase-client-dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - briefcase-network
    command: npm start
    stdin_open: true
    tty: true

networks:
  briefcase-network:
    driver: bridge
