name: Briefcase CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build development containers
        run: docker-compose -f docker-compose.dev.yml build
      
      - name: Run services in test mode
        run: |
          docker-compose -f docker-compose.dev.yml up -d
          docker-compose -f docker-compose.dev.yml run client npm test
          docker-compose -f docker-compose.dev.yml run server npm test
      
      - name: Security scan
        uses: anchore/scan-action@v3
        with:
          image: briefcase-server-dev
          fail-build: true
      
      - name: Archive logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: docker-logs
          path: |
            docker-compose.log
            server.log
            client.log

  scrape-test:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Start services
        run: docker-compose -f docker-compose.dev.yml up -d
      
      - name: Run scraper tests
        run: |
          docker-compose -f docker-compose.dev.yml exec server node test/scraperTest.js
      
      - name: Monitor resource usage
        uses: LucaGiorgi/cpu-memory-usage@v1